name: helloWorldC

on:
  push:
    branches:
      - 'c/**'

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: helloWorld
      run: |
        gcc -o helloWorld main.c
        ./helloWorld