name: helloWorldC

on:
  push:
    branches:
      - 'c/**'

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: helloWorld
      run: |
        gcc -o helloWorld main.c
        ./helloWorld